# --- Notifications Layer Configuration ---
layerrule = animation slide top, match:namespace notifications
layerrule = blur on, match:namespace notifications
layerrule = ignore_alpha -2.5, match:namespace notifications

# --- Rofi Layer Configuration ---
layerrule = animation fade, match:namespace rofi
layerrule = blur on, match:namespace rofi
layerrule = ignore_alpha -2.5, match:namespace rofi

# --- Nwg-dock-hyprland Layer Configuration ---
layerrule = animation slide bottom, match:namespace nwg-dock-hyprland