# See https://wiki.hypr.land/Configuring/Monitors/
################
### MONITORS ###
################

# HDMI monitor
monitor=HDMI-A-1, 1920x1080@60, auto, 1

# Fallback for unknown monitors
monitor=,preferred,auto,1
