#################
### AUTOSTART ###
#################

exec-once = kitty
exec-once = waybar  
exec-once = swaybg -i ~/Downloads/kanagawa.png -m fill
exec-once = wl-paste --type text --watch cliphist store 
exec-once = wl-paste --type image --watch cliphist store
exec-once = systemctl --user start hyprpolkitagent
exec-once = gnome-keyring-daemon --start --components=secrets
exec-once = dbus-update-activation-environment --systemd DISPLAY
exec-once = sunshine
exec-once = mako
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = nwg-dock-hyprland -i 32 -mb 10 -p bottom -c "rofi -show drun" -a center -d -hd 20