# See https://wiki.hypr.land/Configuring/Monitors/
################
### MONITORS ###
################

# Primary laptop monitor - native resolution
monitor=eDP-1, 1920x1080@144, 0x0, 1

# External monitor
monitor=HDMI-A-1, 1366x768@59, auto, 1

# Fallback for unknown monitors
monitor=,preferred,auto,1
